# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Base info
mc_version=26.1.2
neo_version=26.1.2.22-beta

mod_group=xyz.poketech.dyeityourself
mod_id=dyeityourself
mod_archive_name=diy

version = 6.0.0

#Publishing
curseforge_id=291427