modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/Dye-It-Yourself/issues"
license="GPL-3.0"
[[mods]] #mandatory
    modId="dyeityourself"
    version="${file.jarVersion}"
    displayName="Dye It Yourself"
    updateJSONURL="http://raw.githubusercontent.com/Mrbysco/Dye-It-Yourself/master/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/dye-it-yourself"
    #logoFile="logo.png"
    credits=""
    authors="Poke1650, Cazsius, Willbl3pic, Tfarcenim"
    description='''
Lets the sheep dye themselves.
'''

[[dependencies.dyeityourself]]
    modId="neoforge"
    type="required"
    versionRange="[21.11.0-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dyeityourself]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.11,)"
    ordering="NONE"
    side="BOTH"